SETTINGS:
##Do you want the plugin to remember a player's last PVP state when the login
  PERSISTENT_PVP_STATE: false
##How much time a player must wait to use /pvp off/toggle (if pvp is on) in seconds after running the command or being in pvp
  COOLDOWN: 0
##True makes pvp off by default. False makes pvp on by default.
  DEFAULT_PVP_OFF: true
##Show PVP on particle effects
  PARTICLES: true
##SHOW PVP on red nametag
  NAMETAG: false
## Worlds to disable PvP toggling in (i.e. will always use the world's settings)
  BLOCKED_WORLDS: []
##<pvpstate> goes in place of a player's current pvp state
##<parameter> goes in place of a player's name or other parameter
MESSAGES:
  HELP_HEADER: '&a&lCommands:'
  HELP_GENERAL_USEAGE: '&aUse /pvp {toggle|on|off|status} to change/view pvp state.'
  HELP_VIEW_OTHERS: '&aUse /pvp <player> to see another players pvp state.'
  HELP_SET_OTHERS: '&aUse /pvp {toggle|on|off} <player> to set another players pvp state.'
  NO_PLAYER: '&cCould not find a player by the name <parameter>'
  COMMAND_INVALID_PARAMETER: '&c<parameter> is an invalid parameter. {toggle|on|off|status}'
  COMMAND_NO_PERMISSION: '&cYou do not have permission to set others pvp  state.'
  PVP_STATE_ENABLED: '&aYour pvp has been enabled!'
  PVP_STATE_DISABLED: '&aYour pvp has been disabled!'
  PVP_STATE_CHANGED_OTHERS: '&a<parameter> had their pvp state changed to <pvpstate>' 
  PVP_STATUS: '&aYour pvp is set to <pvpstate>'
  PVP_STATUS_OTHERS: '&a<parameter> has their pvp <pvpstate>'
  PVP_DISABLED: '&cYou have pvp disabled!'
  PVP_DISABLED_OTHERS: '&c<parameter> has pvp disabled!'
  PVP_COOLDOWN: '&cToo fast! You can turn off pvp in <parameter> seconds.'
  PVP_WORLD_CHANGE_DISABLED: '&aYour pvp has been disabled because the world you entered does not allow pvp.'
  PVP_WORLD_CHANGE_REQUIRED: '&aYour pvp has been enabled because the world you enter requires pvp.'
  PVP_WORLD_CANNOT_CHANGE_SELF: '&cYou cannot change pvp state in this world.'
  PVP_WORLD_CANNOT_CHANGE_OTHERS: '&cYou cannot change pvp state in that world.'
  PLACEHOLDER_OFF: '&aOff'
  PLACEHOLDER_ON: '&cOn'